INSERT INTO ACCOUNT (ACCOUNTNUMBER, FIRSTNAME, LASTNAME) VALUES(1234, 'JOHN', 'DOE');

INSERT INTO ACCOUNT (ACCOUNTNUMBER, FIRSTNAME, LASTNAME) VALUES (1235, 'JOHN', 'DOE');

INSERT INTO ACCOUNT (ACCOUNTNUMBER, FIRSTNAME, LASTNAME) VALUES (1236, 'JOHN', 'DOE');